name: 'sql_practice'
version: '1.0.0'
config-version: 2

profile: 'sql_practice'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  sql_practice:
    +quote_columns: false

models:
  sql_practice:
    staging:
      +materialized: view
    marts:
      +materialized: table
